### ISSUE TITLE
Roadmap of 2023

### ISSUE THREAD

**Issue by liangping** [ping-pub/explorer#294]
# Roadmap of 2023
`Ping Dashboard` is designed as an basic tool for exploring cosmos blockchain data. It mainly focuses on common basic functions, such as delegation, transfer, voting and so on. With the explosive growth of the Cosmos ecosystem, we need a thorough upgrade to meet the needs of the community.

There are three main goals: 
1.  Reduce the size of the deployment package and improve the first loading speed. 
2.  Enhance version compatibility and improve customization. 
3.  More IBC features.
 
The main tasks include:
## Framework upgrade
- [ ] Vue 2.0 upgrade to 3.0
- [ ] Javascript to Typescript
- [ ] Rest api to grpc

## Customization
- [ ]   SDK version compatible improvements
- [ ]   Multilingual, Internationalization
- [ ]   Module customization
- [ ]   Theme customization (low priority)

## Wallets Integration
 - [ ] Metamask, 
 - [ ] Wallet Connect, 
 - [ ] Cosmostation
 - [ ] Leap
 
## New Features
- [ ] Features for provider chain and consumer chain
- [ ] New IBC features and Improvement, (Transfer, Query, ICA)
- [ ] Governance Improvement
- [ ] Search improvement 
- [ ] NFT wallets/display
- [ ] Smart contract (optional)
- [ ] Widget System

## Sponsor Program
A good open source project is inseparable from the support of sponsors. We are now looking for 1-3 sponsors. We will provide advertising services for one year. Those who are interested can DM me: [![https://discord.gg/CmjYVSr6GW](https://img.shields.io/badge/discord-join-7289DA.svg?logo=discord&longCache=true&style=flat)](https://discord.gg/CmjYVSr6GW)

**Comment by dogemos** [comment]
happy to sponsor this. please get in touch via twitter dm and we can discuss the details!

**Comment by shaneqiuu** [comment]
look forward to more IBC features

**Comment by asalzmann** [comment]
I'm a big fan of ping.pub. Some suggestions
* rewriting in React would make this more accessible to developers 
* adding new IBC features (ICA, ICQ) would give ping.pub a feature that no other explorer has today, as far as I know 
* i18n sounds like a lot of work for not much benefit, since chrome will translate pages for you anyway
* building the ping faucet into the dashboard would be very cool, if this were the case I bet nearly every testnet would use ping.pub by default

**Comment by liangping** [comment]
This is exactly what we want to hear from the community! thank you! @asalzmann 

> * i18n sounds like a lot of work for not much benefit, since chrome will translate pages for you anyway

Haha, It's true. 

> * building the ping faucet into the dashboard would be very cool, if this were the case I bet nearly every testnet would use ping.pub by default

This is a really good idea.

> * rewriting in React would make this more accessible to developers

I don't have much experiences in React.

**Comment by pyramation** [comment]
following :)
